esphome:
  name: teams_presence_led
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Teams Presence Led"
    password: !secret wifi_hotspot_password

captive_portal:

logger:

api:

ota:

web_server:
  port: 80

light:
  - platform: neopixelbus
    type: RGB
    pin: GPIO26 #D26
    num_leds: 12
    variant: WS2812
    method: ESP32_I2S_1
    name: "xringname"    
    id: "xringid"